### ISSUE TITLE
TypeError: unbound method __setitem__() must be called with UserDict instance as first argument (got BeakerSessionDataObject instance instead)

### ISSUE THREAD

**Issue by gelbi123** [collective/Products.BeakerSessionDataManager#8]
Hi,

I am using Zope-4.5.5 with python2.7 and upgraded the BeakerSessionDataManager from
1.1 to 2.1. Now I get the error mentioned in the title. 

Traceback:

```
Traceback (most recent call last):
  File "./bin/zopepy", line 156, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "eggs/Products.BeakerSessionDataManager-2.1-py2.7.egg/Products/BeakerSessionDataManager/userdict_bug.py", line 8, in <module>
    set_object()
  File "eggs/Products.BeakerSessionDataManager-2.1-py2.7.egg/Products/BeakerSessionDataManager/userdict_bug.py", line 5, in set_object
    obj.set("name","Hans")
  File "/opt/wu-wien/zope/buildouts/z4-full-ms/eggs/Products.BeakerSessionDataManager-2.1-py2.7.egg/Products/BeakerSessionDataManager/sessiondata.py", line 137, in mutating_func
    res = func(self, *args, **kw)
TypeError: unbound method __setitem__() must be called with UserDict instance as first argument (got BeakerSessionDataObject instance instead)
```

I created a small python script for debugging with the following code lines

```
from Products.BeakerSessionDataManager.sessiondata import BeakerSessionDataObject  

def set_object():
    obj = BeakerSessionDataObject({})
    obj.set("name","Hans")

if __name__=='__main__':
    set_object()
```

and set a breakpoint in sessiondata.py at line 137

```
133 def session_mutator(func):
134     """Decorator to make a UserDict mutator save the session."""
135 
136     def mutating_func(self, *args, **kw):
137         import pdb; pdb.set_trace()
138         res = func(self, *args, **kw)
139         self.data.save()
140         return res
141 
142     return mutating_func
```
and get the following output

```
-> res = func(self, *args, **kw)
(Pdb) func 
<unbound method UserDict.__setitem__>
(Pdb) self
<Products.BeakerSessionDataManager.sessiondata.BeakerSessionDataObject object at 0x7f5402518110>
(Pdb) self.__class__.__bases__
(<type 'Acquirer'>,)
```

Like in the error message func needed a UserDict instance. So I decided to superclass
the BeakerSessionDataObject with UserDict

```
--- sessiondata.py.ori	2022-06-01 17:53:17.498726128 +0200
+++ sessiondata.py	2022-06-02 09:47:25.634680172 +0200
@@ -142,7 +142,7 @@
 
 
 @implementer(ISessionDataObject)
-class BeakerSessionDataObject(Implicit):
+class BeakerSessionDataObject(UserDict, Implicit):
     """Adapts a beaker session object to the interface expected of Zope sessions."""
 
     security = ClassSecurityInfo()
```

Now this error doesnt appear anymore.

**Comment by mpeeters** [comment]
Hello,

this package no longer support python2.7 since version 2.0, you can try the version 1.1 where UserDict is still used but incompatible with Python 3

**Comment by mpeeters** [comment]
I never encounter any issue with version 1.1 and python2.7, this version should work for you.
